#!/bin/bash

export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

source "$CONFIG_DIR/bar.sh"
source "$CONFIG_DIR/defaults.sh"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# source "$ITEM_DIR/cron.sh"       # node + Notion Calendar API 필요
# source "$ITEM_DIR/weather.sh"    # WeatherAPI 키 필요

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
# source "$ITEM_DIR/cpu.sh"     # tmux와 중복, 필요 시 활성화
# source "$ITEM_DIR/memory.sh"  # tmux와 중복, 필요 시 활성화
# source "$ITEM_DIR/caffeinate.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/music.sh"

sketchybar --update

